research_fi_task:
  description: >
    You are analyzing recent developments in {country}'s fixed income market using the structured search result data below.
    The current date is {current_time}, and your knowledge cutoff is {current_time}.
    Ignore any events or data after this time.

    The input is a JSON blob of recent search results, which includes links, snippets, and article titles.
    YOU MUST base your output on this structured input. Do not attempt to query the internet yourself.
    
    Extract key trends, themes, and noteworthy movements related to {country}'s fixed income markets.
    Focus on government and corporate bonds, foreign flows, yields, issuance, credit risk, or major policy impacts.
    
    Summarize findings using bullet points or short paragraphs grouped by theme when relevant.
  input: >
    Structured news search results for {country}'s fixed income market up to {current_time}:
    {serper_output}
  expected_output: >
    A structured and readable summary of the fixed income market in {country}, including bullet points or short sections that:
    - Highlight meaningful recent developments and macro factors
    - Identify trends that may lead to large future movements
    - Provide quotes or article titles when useful
    If no useful info could be extracted, explicitly say so.
  agent: fixed_income_specalist


# research_fi_task:
#   description: >
#     YOU MUST use the serper_tool before generating your response.
#     If you do not use the serper_tool, your task is incomplete.
#     You are operating with a knowledge cutoff of {current_time}. Ignore
#     all information and data beyond {current_time}.
#     Your task is to collect and summarize relevant recent data, news,
#     and developments in {country}'s fixed income market that occurred 
#     before {current_time} by searching the interent using the input.
#   input: >
#     Recent news and trends in {country}'s fixed income market before {current_time}
#   expected_output: >
#     A breakdown with bullets and descriptions when appropriate detailing
#     general recent trends in a {country}'s fixed income markets 
#     that have a lot of movement or are primed to see movement.
#     If you were unsuccessful at accessing the internet with serper_tool, note
#     that in the final output.
#   agent: fixed_income_specalist

# research_cc_task:
#   description: >
#     YOU MUST use the serper_tool before generating your response.
#     If you do not use the serper_tool, your task is incomplete.
#     You are operating with a knowledge cutoff of {current_time}. Ignore
#     all information and data beyond {current_time}.
#     Your task is to collect and summarize relevant recent data, news,
#     and developments in {country}'s corporate credit market that occurred 
#     before {current_time} by searching the interent using the input.
#   input: >
#     Recent news and trends in {country}'s fixed income market before {current_time}
#   expected_output: >
#     A breakdown with bullets and descriptions when appropriate detailing
#     general recent trends in a {country}'s corporate credit markets 
#     that have a lot of movement or are primed to see movement.
#     If you were unsuccessful at accessing the internet with serper_tool, note
#     that in the final output.
#   agent: corporate_credit_specialist