research_fi_task:
  description: >
    You are operating with a knowledge cutoff of {current_time}. Ignore
    all information and data beyond {current_time}.

    YOU MUST use the SERPER SEARCH TOOL before generating your response.
    When using the Serper search tool, ALWAYS pass only a plain string 
    as the search query. DO NOT wrap it in a dictionary. If you do not use 
    the tool, your task is incomplete.

    Your task is to collect and summarize relevant recent data, news,
    and developments in global fixed income markets that occurred 
    before {current_time}, split by searching for:
      - United States
      - Europe
      - Latin America
      - East-Southeast Asia
      - BRICS
    Start by searching for the United States, then Europe after, then
    continue to the end of the list.
    
    The goal is to prepare an information base
    that a strategist on {current_time} would have access to for 
    making decisions for the coming year.
  expected_output: >
    A breakdown with bullets and descriptions when appropriate detailing
    general recent trends in a few select interesting country's markets 
    that have a lot of movement or are primed to see movement.
  agent: fixed_income_specalist